
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/osiris:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/osiris:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/osiris:$COMMIT_SHA']
